### ISSUE TITLE
Suggestion: Time to Abandon Baby

### ISSUE THREAD

**Issue by JuicyJuuce** [Crumplecorn/ARK-Breeding-Calculator#1]
First off, great tool. I use the "Baby Time" and "Current Buffer" figures extensively so that I know how long I can afk after filling babies with food.

I think a great addition would be something along the lines of "Time to Abandon Baby." This would be the time until you get to the point where filling the baby with food will allow the baby to reach juvenile stage before needing more food.

Also, regarding spoilage, I think for the baby calculations it should automatically assume each raw meat stack will spoil one every 40 minutes and each cooked will every 80 minutes and that each stack is half-way through spoiling one when the dino is filled with food. This will help with high-end dinos like quetzels and gigas where food spoilage during the baby phase can destroy a third of your raw meat (especially during that last stretch right before juvenile when it can hold the most and you can afk the longest).

**Comment by Crumplecorn** [comment]
I've been considering this and looking at the numbers. I think I will modify the baby stats to use the trough calculator for its buffer numbers, after my recent overhaul of the code that should be easy enough to do. I should then be able to get it to estimate the "abandon baby" time.

**Comment by Crumplecorn** [comment]
Added this, not live yet as it needs further bugfixing after the extensive changes I've made recently.
