### ISSUE TITLE
50% minimum cooked meat loss

### ISSUE THREAD

**Issue by Darinth** [Crumplecorn/ARK-Breeding-Calculator#14]
Selecting a carnivore and trying to feed cooked meat always results in at least 50% loss. Gives the correct time, but still reports 50% loss.

Tried clearing cookies to see if maybe it was simply something on my end. Tested in both chrome (my default) and firefox.

**Comment by Crumplecorn** [comment]
Cooking meat halves the food value (except in special cases like the daeodon), so loss will always be a minimum of 50%.

**Comment by Darinth** [comment]
Ahh. Okay, I read that as a '50% cooked meat would spoil', makes more sense now.
