### ISSUE TITLE
deinonychus

### ISSUE THREAD

**Issue by DeerHunter666** [Crumplecorn/ARK-Breeding-Calculator#15]
Please add deinonychus

**Comment by TafThorne** [comment]
If no one else looks at this soon I shall try to get the latest development pack from Ark which hopefully includes the new dinos for the new expansion.

**Comment by DeerHunter666** [comment]
Appreciate your efforts

**Comment by Crumplecorn** [comment]
If you can get the latest data from the dev kit I'll push it to live, dev kit wouldn't even run for me the last time I tried.

**Comment by DeerHunter666** [comment]
@TafThorne any luck with the development pack?

**Comment by TafThorne** [comment]
It was not straight forward and then I ran out of time and did not get back to it.  Sorry for the long delay.

**Comment by DeerHunter666** [comment]
@TafThorne all good, hope you can around to it shortly

**Comment by DevlinDelFuego** [comment]
I committed a edit. The Deinonychus uses the same settings as a Raptor.

**Comment by PiTi2k5** [comment]
https://github.com/Crumplecorn/ARK-Breeding-Calculator/pull/26

**Comment by DeerHunter666** [comment]
Thankyou
