### ISSUE TITLE
Any plans to add the aberration dinos?

### ISSUE THREAD

**Issue by trapper-** [Crumplecorn/ARK-Breeding-Calculator#2]

**Comment by Crumplecorn** [comment]
I'm not actively playing Ark at the moment and have limited time, so updates from me are going to be slow, but I don't intend to stop updating completely.

Once the creatures are in the dev kit (they may already be, I must check), I can start adding them over time.

**Comment by SpawnOrion** [comment]
I believe they are.  I could help, but I haven't gotten the hang of the code yet.  If you have any advice, I could help.

**Comment by trapper-** [comment]
I think we just need to get the data into this format then add them all to
controller.js

Ankylosaurus: {
birthtype: "Incubation",
type: "Herbivore",
basefoodrate: 0.003156,
babyfoodrate: 25.5,
extrababyfoodrate: 20.0,
agespeed: 0.000003,
agespeedmult: 1.9,
eggspeed: 0.005556,
eggspeedmult: 1.9,
weight: 250
},

**Comment by SpawnOrion** [comment]
Okay.  I should have time this weekend and I'll try to get this done.

**Comment by Crumplecorn** [comment]
Yes, the brief [guide](http://crumplecorn.com/content/breeding-calculator) I wrote outlines where to get the values in the dev kit, though it may be a bit out of date. What I usually do is copypaste an existing dino of the same type (herbi vs carni, incubate vs gestate) and then go through and replace the numbers.

Once it's in the list in controller.js it will appear in the calculator.

**Comment by tsolron** [comment]
I put a bunch of these into a pull request. I skipped the special ones like Rock Drakes and Reaper Kings

**Comment by Crumplecorn** [comment]
tsolron's changes merged and put live. Nice work!

And yes, special ones like drakes wouldn't make sense in this calculator as the considerations are quite different.
