### ISSUE TITLE
interface updated?

### ISSUE THREAD

**Issue by hiimzech** [Crumplecorn/ARK-Breeding-Calculator#20]
I can see the codes are updated on github but I don't know how their deployment works.
can I get a confirmation http://ark.crumplecorn.com/breeding/ is using the new stack size of 40 for raw meat?

**Comment by Crumplecorn** [comment]
Yes the deployed version is using the new stack sizes.

**Comment by TafThorne** [comment]
Maybe we could update the hover text from "Stacks of <food> in the trough" to "Stacks of 40 <food> in the trough".  Would that be clear?

**Comment by hiimzech** [comment]
absolutely. any hint whatsoever that the website is up to date will be great

**Comment by Crumplecorn** [comment]
Good idea, I've changed the hover text as suggested and also mentioned the update in the subheader, and pushed the changes to the live version.

**Comment by TafThorne** [comment]
Looks like this is live and working.
I think this issue can be closed.
