### ISSUE TITLE
Hyaenodon

### ISSUE THREAD

**Issue by chiefsfan15** [Crumplecorn/ARK-Breeding-Calculator#21]
Unless I keep missing it on the list, hyaenodon is not on the breeding calculator. Any chance it will be added?

**Comment by TafThorne** [comment]
I agree that it is not on the list at present. 
![Hyaenodon Not Listed](https://user-images.githubusercontent.com/586550/82316072-32043e00-99c4-11ea-9b72-da0d890f83a8.png)

**Comment by PiTi2k5** [comment]
https://github.com/Crumplecorn/ARK-Breeding-Calculator/pull/26
