### ISSUE TITLE
Ichthyornis never added

### ISSUE THREAD

**Issue by Ichthyornisfan** [Crumplecorn/ARK-Breeding-Calculator#24]
Crumple, my love, I made this account just to tell you you never added the Ichthyornis.

I've been breeding these fucking gulls for way longer than anyone ever should because I geniunly have nothing better to do with my life and my fwb is busy finals so it's not like I'm getting laid anyway. But I have a favorite species of seagull IRL so that shouldn't be a wonder (its the great black backed gull, thank you all for wondering, I know you were.)
I've been using the pelagornis setting. The problem is the ichthyornis have like a third of the weight so I don't know how accurate the "hand feed until" time is and I might have wasted even more of my life while I'm having an identity crisis over no longer being a teenager.

Please make my life slightly less loser like and add the ichthyornis so I can go out and find some more dick instead of feeding virtual seagulls for longer than absolutely necessary.

Jokes aside plz ad it and thank you for all you've done for the community.

**Comment by TafThorne** [comment]
Odd that I did not notice this when I have berd the gulls a few times to get pearls and magical fish!

![Missing Ichthyornis](https://user-images.githubusercontent.com/586550/84366848-4efaee00-abcb-11ea-91ca-40c1cab5bb02.png)

Bug confirmed in current version.  Maybe one day I will get a PC and be able to get the dev kit working.

**Comment by PiTi2k5** [comment]
https://github.com/Crumplecorn/ARK-Breeding-Calculator/pull/26

**Comment by PiTi2k5** [comment]
https://github.com/Crumplecorn/ARK-Breeding-Calculator/pull/26
