### ISSUE TITLE
please add calculation for Carcharodontosaurus

### ISSUE THREAD

**Issue by hiimzech** [Crumplecorn/ARK-Breeding-Calculator#43]
Carcharodontosaurus

its the latest one. supposed to be the last dino but wc seems undecided about it recently
https://ark.wiki.gg/wiki/Carcharodontosaurus

**Comment by arnobeck** [comment]
Hi,

I've created a pull request for that : https://github.com/Crumplecorn/ARK-Breeding-Calculator/pull/44

**Comment by TafThorne** [comment]
Looks like this issue is resolved.  Thank you @arnobeck for your pull request and @hiimzech you can hopefully see the option to model the new creature live on the website now.
