### ISSUE TITLE
Gigantoraptor Base weight

### ISSUE THREAD

**Issue by ArkHelpCenter** [Crumplecorn/ARK-Breeding-Calculator#47]
When choosing the creature Gigantoraptor, the base weight is always set to 380 by default. However, the actual base weight of a Gigantoraptor is 320.

It would be beneficial if the default value could be updated, as it might cause people to lose their low level gigantoraptors if they do not pay attention to the weight.

**Comment by Crumplecorn** [comment]
Fixed
