### ISSUE TITLE
Request: higher Desired Buffer values.

### ISSUE THREAD

**Issue by deedoubleu** [Crumplecorn/ARK-Breeding-Calculator#6]
I can't calculate desired buffer of 8h because field is capped at 300 minutes.

**Comment by Crumplecorn** [comment]
Raised limit to 600 minutes. RIP mobile users who mistype.

I don't think any creature can reach/exceed a ten hour buffer within its baby phase, regardless when you start going north of 700-800 even a desktop processor starts to feel the pain.
