### ISSUE TITLE
Snow Owl Consumption Rate Patched

### ISSUE THREAD

**Issue by Cassidy-Blake** [Crumplecorn/ARK-Breeding-Calculator#9]
Baby snow owl consumption rate has been adjusted in patch 288.113 to consume significantly less meat. This rate has yet to be reflected within the breeding calculator or trough calculator.

**Comment by Crumplecorn** [comment]
I'll check the dev kit to see if it has the updated values.

**Comment by fleurbrawl** [comment]
We've been doing some raising experiments with Argies and Owls to compare the food rates as the raise time is fairly similar, and it looks as thought the Snow Owl rate is definitely off as they both eat at a similar rate will raising.
You have the Argie rate at
basefoodrate: 0.001852,
And the Snow Owl at
basefoodrate: 0.01,

I don't have access to the dev kit to actually see the correct values, but would seem like the Owl should be a lot closer to the Argie value.

**Comment by TafThorne** [comment]
I am happy to overfeed a baby but would be annoyed if we left it.  If the correct value cannot be found, please consider a conservative update or no update.

**Comment by fleurbrawl** [comment]
Trough calculations with the current numbers are quite scary, 20 owls on 10 troughs was coming out at 3 hours - in game, only 2.5 troughs were used overnight.

**Comment by Crumplecorn** [comment]
Dev kit won't open for me - runs out of memory, so I'm having trouble checking the numbers D:

**Comment by PiTi2k5** [comment]
https://github.com/Crumplecorn/ARK-Breeding-Calculator/pull/26
